DELETE FROM Users;
DELETE FROM Courses;
DELETE FROM Assessments;
DELETE FROM Results;
DELETE FROM UserCourses;
DELETE FROM Reviews;
DELETE FROM UserFollowings;
DELETE FROM CourseTags;
DELETE FROM Tags;

ALTER TABLE Courses DROP CONSTRAINT [FK_Courses_Users];
ALTER TABLE Assessments DROP CONSTRAINT [FK_Assessments_Users];
ALTER TABLE Assessments DROP CONSTRAINT [FK_Assessments_Courses];
ALTER TABLE Results DROP CONSTRAINT [FK_Results_Users];
ALTER TABLE Results DROP CONSTRAINT [FK_Results_Assessments];
ALTER TABLE UserCourses DROP CONSTRAINT [FK_UserCourses_Users];
ALTER TABLE UserCourses DROP CONSTRAINT [FK_UserCourses_Courses];
ALTER TABLE Reviews DROP CONSTRAINT [FK_Reviews_Users];
ALTER TABLE Reviews DROP CONSTRAINT [FK_Reviews_Courses];
ALTER TABLE UserFollowings DROP CONSTRAINT [FK_UserFollowings_Users];
ALTER TABLE UserFollowings DROP CONSTRAINT [FK_UserFollowings_Followers];
ALTER TABLE Course_Tags DROP CONSTRAINT [FK_CourseTags_Users];
ALTER TABLE Course_Tags DROP CONSTRAINT [FK_CourseTags_Tags];

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Assessment;
DROP TABLE IF EXISTS Results;
DROP TABLE IF EXISTS UserCourses;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS UserFollowings;
DROP TABLE IF EXISTS CourseTags;
DROP TABLE IF EXISTS Tags;


CREATE TABLE [Users](
Id VARCHAR(64) NOT NULL PRIMARY KEY IDENTITY,
firstName VARCHAR(64) NOT NULL,
lastName VARCHAR(64) NOT NULL,
[password] VARCHAR (64) NOT NULL,
username VARCHAR (64) NOT NULL,
phoneNumber VARCHAR (64),
userStatus INT NOT NULL,
[create] BIT NOT NULL,
reg BIT NOT NULL,
summary BIT NOT NULL,
courses BIT NOT NULL
);

CREATE TABLE Courses(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
title VARCHAR(96) NOT NULL,
[description] VARCHAR (704) NOT NULL,
category VARCHAR (64) NOT NULL,
topic VARCHAR (64) NOT NULL,
code VARCHAR (32),
tags VARCHAR (32),
userId VARCHAR NOT NULL,
CONSTRAINT FK_Courses_Users FOREIGN KEY(userId) REFERENCES [Users](Id)
);

CREATE TABLE Assessments(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
courseId VARCHAR NOT NULL,
totalTime INT,
title VARCHAR(96) NOT NULL,
[description] VARCHAR(320) NOT NULL,
masteryScore INT NOT NULL,
userId VARCHAR NOT NULL,
CONSTRAINT FK_Assessments_Users FOREIGN KEY(userId) REFERENCES [Users](Id),
CONSTRAINT FK_Assessments_Courses FOREIGN KEY(courseId) REFERENCES [Courses](Id)
);

CREATE TABLE UserCourses(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
userId VARCHAR NOT NULL,
courseId VARCHAR NOT NULL,
CONSTRAINT FK_UserCourses_Users FOREIGN KEY(userId) REFERENCES [Users](Id),
CONSTRAINT FK_UserCourses_Courses FOREIGN KEY(courseId) REFERENCES Courses(Id)
);

CREATE TABLE Results(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
userId VARCHAR NOT NULL,
assessmentId VARCHAR NOT NULL,
scoreRaw INT NOT NULL,
sessionTime INT NOT NULL,
lessonStatus VARCHAR NOT NULL,
CONSTRAINT FK_Results_Users FOREIGN KEY(userId) REFERENCES [Users](Id),
CONSTRAINT FK_Results_Assessments FOREIGN KEY(assessmentId) REFERENCES Assessments(Id)
);

CREATE TABLE Reviews(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
userId VARCHAR NOT NULL,
courseId VARCHAR NOT NULL,
difficulty INT NOT NULL,
content INT NOT NULL,
design INT NOT NULL,
assessments INT NOT NULL,
exercises INT NOT NULL,
relevancy INT NOT NULL,
overview VARCHAR,
CONSTRAINT FK_Reviews_Users FOREIGN KEY(userId) REFERENCES [Users](Id),
CONSTRAINT FK_Reviews_Courses FOREIGN KEY(courseId) REFERENCES Courses(Id)
);

CREATE TABLE Tags(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
[name] VARCHAR (128) NOT NULL
);

CREATE TABLE CourseTags(
Id VARCHAR (128) NOT NULL PRIMARY KEY IDENTITY,
courseId VARCHAR NOT NULL,
tagId VARCHAR NOT NULL,
CONSTRAINT FK_CourseTags_Courses FOREIGN KEY(courseId) REFERENCES Courses(Id),
CONSTRAINT FK_CourseTags_Tags FOREIGN KEY(tagId) REFERENCES Tags(Id)
);